# -*- coding: utf-8 -*-
"""AndresT_AA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13j-SOI09nNzmzg72zQ7iJQ58BJ6nbZck
"""

import pandas as pd

AA=pd.DataFrame(columns=['criteria' ,'weight', 'ratingA','ratingB', 'scoreA', 'scoreB',])
print(AA)

AA['criteria']=['risk','ROI','customerSatisfaction','feasibility','strategicAlignment']
print(AA)

AA['weight']=[0.1,0.15,0.3,.15,.3]
print(AA)

AA['ratingA']=[4,1,2,1,5]
AA['ratingB']=[3,4,2,3,2]

##Step 4: calculate partial scores by 

for index, row in AA.iterrows():
  AA['scoreA'][index]=row['ratingA']*row['weight']
  AA['scoreB'][index]=row['ratingB']*row['weight']

print(AA)

totalScoreA=0
totalScoreB=0
for index, row in AA.iterrows():
  totalScoreA+=row['scoreA']
  totalScoreB+=row['scoreB']

print ('the total score for A is {:.2f} and for B is {:.2f}'.format(totalScoreA, totalScoreB))
